apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cultigestapp
  template:
    metadata:
      labels:
        run: cultigestapp
    spec:
      containers:
      - name: cultigestapp
        image: docsourav1992/cultigestapp
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent
